name: "Release"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate and release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate HACS Integration
        uses: hacs/action@main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        if: startsWith(github.ref, 'refs/tags/')
